const projects = [{
        img: "../imgs/Devilslist.png",
        title: "Decentralized Angellist",
        tech_stack: "Tezos, IPFS, React JS",
        date: "July 21, 2022",
        description: "DevilsList is an end-to-end platform where investors may invest in businesses using tez/USDT and sign SAFT/SAFEs directly on the site. When a round closes, this website keeps track of the cap-table, and entrepreneurs may pay their workers and vendors in tez/USDT",
        live: "https://decentralizedangellist.web.app/",
        github: "https://github.com/Dragonglass101/Decentralized-AngelList",
    },
    {
        img: "../imgs/cuphead.png",
        title: "Cuphead Clone",
        tech_stack: "SDL Graphics Library",
        date: "November 19, 2021",
        description: "",
        live: "",
        github: "https://github.com/Dragonglass101/CPP-Project",
    }, {
        img: "../imgs/critical-point-visualization.png",
        title: "Betti Number Calculation",
        tech_stack: "Three JS",
        date: "April 24, 2022",
        description: "This is a visualization of critical points of a smooth manifold calculated using Morse Theory in order to find Betti numbers of a given surface",
        live: "https://dragonglass101.github.io/Critical-Point-Visualization/",
        github: "https://github.com/Dragonglass101/Critical-Point-Visualization",
    }, {
        img: "../imgs/sportify.png",
        title: "Sportify",
        tech_stack: "Firebase, React JS",
        date: "March 21, 2022",
        description: "A web application to manage sports tournaments and show live scores of different events. Was used for IIITB Sports Fest, Spandan. It provides the following functionalities: Users can view live scores, Admins can create and manage fixtures, Admins can update the score board",
        live: "https://sportify-8829a.web.app/",
        github: "https://github.com/Bondok6/Reservify",
    },
]